{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-promises
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/promises_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/promises/promises_{{ version }}.tar.gz
  sha256: bb68fd4065cc072996aed416f0b2388f58738797a3a38024720c29d67164747d

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-r6                         # [build_platform != target_platform]
    - r-fastmap >=1.1.0            # [build_platform != target_platform]
    - r-later                      # [build_platform != target_platform]
    - r-lifecycle                  # [build_platform != target_platform]
    - r-magrittr >=1.5             # [build_platform != target_platform]
    - r-otel >=0.2.0               # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-fastmap >=1.1.0
    - r-later
    - r-lifecycle
    - r-magrittr >=1.5
    - r-otel >=0.2.0
    - r-rlang
    - r-rcpp
  run:
    - r-base
    - r-r6
    - r-fastmap >=1.1.0
    - r-later
    - r-lifecycle
    - r-magrittr >=1.5
    - r-otel >=0.2.0
    - r-rlang
    - r-rcpp

test:
  commands:
    - $R -e "library('promises')"           # [not win]
    - "\"%R%\" -e \"library('promises')\""  # [win]

about:
  home: https://rstudio.github.io/promises
  dev_url: https://github.com/rstudio/promises
  license: MIT
  summary: Provides fundamental abstractions for doing asynchronous programming in R using promises. Asynchronous programming is useful for allowing a single R process to orchestrate multiple tasks in the background while also attending to something else. Semantics are similar to 'JavaScript' promises, but with a syntax
    that is idiomatic R.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
    - philip-khor
