appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: VZfUrXUEXXHkuff/dFl4sDz7BOHoa1Ugo+gT2prbXnt7tvxvWRYv2WSasVga/TdN6ElogmJMQQe5uVn4d+Pd6g3yTIf/+qqgTdSstgUNmuh+rT4iNyQT9FzZPX4bTDHuDBVbAV5TAeb2eHCpQn4bljVwLsd03u23EfS1ROXUZrwFBWUkqQ6VodfwX/prYcmBtD3Wi/B3PvotxbKzxZ1Z1R709nFcGwnQENTPNvznXZKn8E5+i4g1xi4dWAlQKmjjJiN49ucpu7jHsDtMHUasHE3HRarlYjiDSu/lddo07DbZ0P0ByQNKhsAO7zO2bLmAAJ7iDMxnn9YbT3mRlYcxRYfqHt4aRA9MG3INIruwqLIvHB/sknURSbj3vMeZI22YMNUvaxjrEEn36Qr12xwRq6i90rOZqvQwhU9oo5GYJ+uvCzJ390h2aXdyx32AKMmYkHa3KwDixO1WFNRDJzjy06uqUwDI5PWISmQdyj5pEdIbzdBksW9BNUnr/Govsb0hJ5Qv3fzR8TvzihQHHFKGGy9DGgzPtFfZ0iYe6hpIV/0qCLxbd50jvdyEJ6yeia/OxkmPRfwFrOuQpV/MnVaQZuQsQ1j4l6hf2H6MHS8hsAtdmHmce5Ejzeo1bTQAmxlFnymk5HlC0X4oklJlPDZMHglfxZKu0DqGWrBBF8PImhI=}
bot:
  automerge: true
